### ISSUE TITLE
complete eda code for gamestop csv

### ISSUE THREAD

**Issue by jtabalon** [Avoiding-Regression/reddit_classification#1]

**Comment by brip1258** [comment]
https://github.com/Avoiding-Regression/reddit_classification/pull/17

**Comment by jtabalon** [comment]
Code looks good! However, when the plots appear on the screen (especially the histogram) it may be unclear which plots belong to what subreddit. It might be helpful to label the following:
- x-axis
- y-axis
- title
Do you mind doing that in this ticket? Or should we open a new issue for that?

**Comment by jtabalon** [comment]
Went ahead and merged this in - gonna create a new issue to capture the labeling of the plots.
